### ISSUE TITLE
v10.x?

### ISSUE THREAD

**Issue by neverfox** [Svakinn/typeahead.js#1]
I don't believe many of the useful features of this fork have been added to the main project, but I was wondering if this fork was going to bring itself up-to-date with the main project in other aspects? Or is that not possible in order to preserve these extra features?

**Comment by Svakinn** [comment]
Most of all I would like the main project to include features of this fork.  However it looks like the authors of typeahead seem to have other ideas than me about what features are most important for auto completion library.
This fork is more or less driven by supplying necessary features for my production projects and as is, quite sufficient for that purpose.
So at the moment I am sorry to say that there are no plans on chasing newer versions of typeahead in this fork.
